### ISSUE TITLE
Problems with installing the player's head skin

### ISSUE THREAD

**Issue by BrainRTP** [AbstractMenus/minecraft-plugin#1]
```
[13:42:19 WARN]: [AbstractMenus] Error while building ItemStack: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[13:42:19 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[13:42:19 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[13:42:19 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[13:42:19 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[13:42:19 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)

-----

[AbstractMenus] Error while building ItemStack: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[17:35:13 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[17:35:13 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[17:35:13 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[17:35:13 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[17:35:13 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.util.bukkit.Skulls.getCustomSkull(Skulls.java:41)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.util.bukkit.Skulls.getPlayerSkull(Skulls.java:66)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.data.properties.PropSkullOwner.apply(PropSkullOwner.java:37)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.item.SimpleItem.applyProperties(SimpleItem.java:88)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.item.SimpleItem.build(SimpleItem.java:66)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.SimpleMenu.placeItems(SimpleMenu.java:76)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.SimpleMenu.refresh(SimpleMenu.java:63)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.SimpleMenu.open(SimpleMenu.java:44)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.services.MenuManager.openMenu(MenuManager.java:102)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.services.MenuManager.openMenu(MenuManager.java:88)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.data.actions.ActionMenuOpen.activate(ActionMenuOpen.java:28)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.data.Actions.activate(Actions.java:75)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.data.Actions.activate(Actions.java:86)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.item.MenuItem.doClick(MenuItem.java:31)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.menu.AbstractMenu.click(AbstractMenu.java:369)
[17:35:13 WARN]:        at AbstractMenus-1.17.2-beta.jar//ru.abstractmenus.listeners.InventoryListener.onInventoryClick(InventoryListener.java:95)
[17:35:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor303.execute(Unknown Source)
[17:35:13 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:35:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:35:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:35:13 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:35:13 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:35:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[17:35:13 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3306)
[17:35:13 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[17:35:13 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[17:35:13 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[17:35:13 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:35:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[17:35:13 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[17:35:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[17:35:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1673)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342)
[17:35:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[17:35:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[17:35:13 ERROR]: [AbstractMenus] Cannot refresh menu item: Cannot invoke "org.bukkit.inventory.ItemStack.getAmount()" because "<local5>" is null
```

<details><summary>Menu config</summary>
<p>

```hocon
title: "Generated Menu"
size: 4
activators {
  command: "gmenu"
}
catalog {
  type: PLAYERS
}

matrix {
  cells: [
    "---------",
    "-xxxxxxx-",
    "-xxxxxxx-",
    "---------"
  ]
  templates {
    "x" {
      skullOwner: "%ctg_player_name%"
      name: "&7Player &e%ctg_player_name%"
    }
  }
}
```

</p>
</details>

**Comment by BrainRTP** [comment]
Cannot be reproduced due to insufficient data.
